//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPTBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.orders = new HashSet<order>();
        }
    
        public int acc_id { get; set; }
        [Display(Name = "User name")]
        public string acc_name { get; set; }
        [Display(Name = "Password")]
        public string password { get; set; }
        [Display(Name = "Full name")]
        public string full_name { get; set; }
        [Display(Name = "Gender")]
        public string gender { get; set; }
        [Display(Name = "Email")]
        public string email { get; set; }
        [Display(Name = "Address")]
        public string address { get; set; }
        public string state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
