//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPTBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.order_detail = new HashSet<order_detail>();
        }

        [Display(Name = "Book id")]
        public string book_id { get; set; }
        [Display(Name = "Book name")]
        public string book_name { get; set; }
        [Display(Name = "Category id")]
        public string cate_id { get; set; }
        [Display(Name = "Price")]
        public int book_price { get; set; }
        [Display(Name = "Quantity")]
        public int book_quantity { get; set; }
        [Display(Name = "Image")]
        public string book_picture { get; set; }
        [Display(Name = "Author")]
        public string book_author { get; set; }
        [Display(Name = "Description")]
        public string book_description { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }
    }
}
